"""baseline_existing_schema

Revision ID: 0001
Revises:
Create Date: 2026-06-02 10:48:05.464544

Baseline migration for the unified monorepo (WO v4.12). It materialises the
*entire current Cost Calculator schema* exactly as defined by the SQLAlchemy
models. Rather than the autogenerated per-table DDL (which emitted mutually
dependent foreign keys inline and would fail under PostgreSQL's strict creation
ordering), the baseline delegates to SQLAlchemy's metadata, which is cycle-aware
and emits the cross-dependent FKs via ALTER after the tables exist — the same
code path the app used under create_all() on SQLite/MySQL, now captured under
Alembic versioning.

All objects are created in the icb_costings schema (the icb_app role's default
search_path). The icb_mes schema is created by deploy/postgres/init.sql and is
populated in later phases.
"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create every table defined by the application models."""
    from app.database import Base
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    """Drop every application table. CASCADE breaks the mutually-dependent
    foreign-key cycles that a dependency-sorted drop_all() cannot resolve."""
    from app.database import Base
    for table_name in Base.metadata.tables:
        op.execute(f'DROP TABLE IF EXISTS "{table_name}" CASCADE')
